MAINT: Allow failures when pulling images, modified

diff --git a/.github/workflows/dtool-lookup-framewok-generic-container-image-build-and-test.yml b/.github/workflows/dtool-lookup-framewok-generic-container-image-build-and-test.yml
--- a/.github/workflows/dtool-lookup-framewok-generic-container-image-build-and-test.yml
+++ b/.github/workflows/dtool-lookup-framewok-generic-container-image-build-and-test.yml
@@ -187,10 +187,10 @@ jobs:
         docker-compose ${DOCKER_COMPOSE_OPTS} config
 
     - name: Pull images
-      continue-on-error: true
       run: |
         cd dtool-lookup-server-container-composition
-        docker-compose ${DOCKER_COMPOSE_OPTS} pull 
+        # don't fail if some image is not publically available
+        docker-compose ${DOCKER_COMPOSE_OPTS} pull || true
         echo "docker image ls"
         docker image ls
 
